version: '3.8'
services:
  impacta-backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
    environment:
      - GIN_MODE=release

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - default
    restart: unless-stopped

volumes:
  grafana-storage: